import Head from "next/head";
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle,
        AiFillLinkedin,
        AiFillYoutube,
        AiFillGithub,
      } from 'react-icons/ai'
import Image from "next/image";
import deved from '../public/memoji.png';
export default function Home(){
  return(
    <div>
      <Head>
        <title> Mati Nemera Protfolio</title>
        <meta name ='description' content = 'Generated by create next app'/>
        <link rel ='icon' href ='/favicon.ico'/>
      </Head>
      <nav className = " py-5 px-10 flex justify-between">
            <h1 className="text-xl font-burtons"> Mati Nemera</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer"/>
              </li>
              <li>
                <a  
                className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white 
                px-4 py-2 border-none rounded-md ml-8" href = "#">Resume</a>
              </li>
            </ul>
          </nav>
      <main className ="bg-white px-10 md:px-20">
        <section>
          
          <div className="pt-20 pb-10">
            <div className="mx-auto flex-row justify-center lg:px-60">
              <h4 className="text-s pb-2 font-medium">Hi, my name is </h4>
              <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-8xl"> Mati Nemera.</h2>
              <h2 className="text-4xl py-1  text-gray-300 font-medium md:text-6xl"> I build things for the web.</h2>
              {/* <h2 className="text-2xl py-2"> Software Engineer </h2> */}
              <p className="text-md py-5 leading-8 text-gray-700 max-w-xl"> 
              I specialize in <span className="text-teal-600">backend engineering</span>, crafting robust solutions for digital ecosystems.
              My focus is on building efficient and scalable software infrastructure.
              </p>
              <h1 className="text-m py-1 text-gray-400"> In short, I turn caffine into software. </h1>
            </div>
          </div>
          <div className="relative mx-auto px-10 bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 overflow-hidden"> 
              <Image src={deved} layout="fill" objectFit="cover"/>
          </div>
          <div className="pt-10 text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <AiFillLinkedin className="text-teal-600"/>
            <AiFillGithub className="text-teal-600"/>
          </div> 
          
        </section>

        <section> 
          <div className="lg:px-60">
            <h3  className="text-teal-600 text-2xl font-medium pt-5 pb-2 font-burtons">About Me</h3>
            <p className=" text=md py-2 leading-8 text-gray-800"> 
              {/* <strong>
                Hey there, I'm Mati, and I'm all about bringing cool ideas to life on the web.
              </strong> */}
            </p>
            <p className="mx-auto text-md text-md py-2 leading-8 text-gray-800">
              My journey began in 2016 when I decided to dive into the world of <span className="text-teal-600">HTML</span> and <span className="text-teal-600">CSS</span>. 
              Coding quickly became my creative outlet, and I was hooked. Starting with front-end development, 
              I soon ventured into the back-end, embracing the full-stack experience.
            </p>
            <p className=" text=md py-2 leading-8 text-gray-800">
              Fast forward to today, and I hold a <span className="text-teal-600">Computer Science degree</span>. Along the way, I’ve had the privilege of working on a handful of meaningful projects. One highlight? Leading a team to victory in the <span className="text-teal-600">NASA-GLEAM Lunar Robotics competition</span> – yep, we absolutely rocked it!
            </p>

            <p className=" text=md py-2 leading-8 text-gray-800"> 
              My focus these days? Creating digital solutions that can make a positive impact. I'm also an avid learner, constantly exploring the latest in technology because, well, I love diving into new things.When I'm not in front of the screen, you can find me on the soccer field, taking a refreshing swim, or simply enjoying good company. Life's an adventure, and I'm here to make it count.
            </p>
          </div>
          <h3  className="text-teal-600 text-2xl font-medium pt-8 pb-2 font-burtons">Tech Stack</h3>
          <div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <h4 className="text-xl first-line:font-medium pb-2 text-teal-600 py-4">Frontend Development</h4>
              <p className="text-gray-800 py-1">HTML5</p>
              <p className="text-gray-800 py-1">CSS</p>
              <p className="text-gray-800 py-1">React</p>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">TypeScript</p>
                
            </div>
          </div>
          <div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <h4 className="text-xl first-line:font-medium pb-2 text-teal-600 py-4">Backend Development</h4>
              <p className="text-gray-800 py-1">Python</p>
              <p className="text-gray-800 py-1">Java</p>
              <p className="text-gray-800 py-1">JDBC</p>
              <p className="text-gray-800 py-1">Javalin</p>
              <p className="text-gray-800 py-1">Maven</p>
              <p className="text-gray-800 py-1">Django</p>
              <p className="text-gray-800 py-1">Flask</p>
              <p className="text-gray-800 py-1">PostgreSQL</p>
              <p className="text-gray-800 py-1">MySQL</p>
            </div>
          </div>
        </section>
        <section>
          <div className=" lg:px-60"> 
            <h3 className="text-teal-600 text-2xl font-medium pt-8 pb-2 font-burtons">Where I've worked</h3>
            {/* <h2> */}
              <div>
                <p className="t"> Software Engineer <span className=" text-teal-500">@Revature</span></p>
                <p className="text-m pt-2 pb-5 text-gray-400"> May 2023 - Present</p>
                <ul>
                  <li className="flex items-start"> 
                    <span className="text-teal-600 text-sm" style={{width: '1.25rem'}}> &gt; </span>
                    <p className="pl-2 pb-1">
                      Designed and developed a user-friendly social media platform, focusing on enhancing performance and user experience.
                    </p>
                  </li>

                  <li className="flex items-start"> 
                    <span className="text-teal-600 text-sm" style={{width: '1.25rem'}}> &gt; </span>
                    <p className="pl-2 pb-1">
                      Implemented comprehensive features enabling users to easily manage their accounts and messages, streamlining their interactions.
                    </p>
                  </li>

                  <li className="flex items-start"> 
                    <span className="text-teal-600 text-sm" style={{width: '1.25rem'}}> &gt; </span>
                    <p className="pl-2 pb-1">
                      Ensured the reliability of user data and minimized errors through effective data management techniques, resulting in a smoother user experience.                 
                    </p>
                  </li>
                </ul>
              </div>
            {/* </h2> */}
          </div>
        </section>
        
        <section>
        <div className="lg:px-60"> 
            <h3 className="text-teal-600 text-2xl font-medium pt-8 pb-2 font-burtons">Projects</h3>
            {/* <h2> */}
              <div>
                <p className="text-lg pt-2"> NASA Gleam Lunar Robotics Challenge </p>
                <p className="text-m pt-0 pb-5 text-gray-400"> October 2021 – April 2022</p>
                <ul>
                  <li className="flex items-start"> 
                    <strong><span className="text-teal-600 text-sm" style={{width: '1.25rem'}}> &gt; </span></strong>
                    <p className="pl-2 pb-1">
                    Team leader in Rover Communications where I implemented live stream from rover camera (raspberry pi 2) through UCP, which improved stream lag by 5 seconds compared to TCP.                    </p>
                  </li>

                  <li className="flex items-start"> 
                  <strong><span className="text-teal-600 text-sm" style={{width: '1.25rem'}}> &gt; </span></strong>
                    <p className="pl-2 pb-1">
                    Programmed a python script to collect and organize data from LIDAR sensor (150 length array), LEDs, IMU, Magnetometer, and Accelerometer.                    </p>
                  </li>

                  <li className="flex items-start"> 
                  <strong><span className="text-teal-600 text-sm" style={{width: '1.25rem'}}> &gt; </span></strong>
                    <p className="pl-2 pb-1">
                    Devised an interface that showed all the sensor information in real-time to navigate the course on the day of the competition.                    </p>
                  </li>
                </ul>
              </div>
            {/* </h2> */}
          </div>

          <div className="lg:px-60"> 
            {/* <h2> */}
              <div>
                <p className="text-lg pt-5"> Weather Application </p>
                <p className="text-m pt-0 pb-5 text-gray-400"> January 2021 – April 2021</p>
                <ul>
                  <li className="flex items-start"> 
                  <strong><span className="text-teal-600 text-sm" style={{width: '1.25rem'}}> &gt; </span></strong>
                    <p className="pl-2 pb-1">
                      Pair programmed and collaborated with teammates in building a weather application that pulls data through an Application Programming Interface (API) in Java.      
                    </p>
                  </li>

                  <li className="flex items-start"> 
                  <strong><span className="text-teal-600 text-sm" style={{width: '1.25rem'}}> &gt; </span></strong>
                    <p className="pl-2 pb-1">
                      Executed live weather updates for 5 Minnesota cities through the use of webhooks. This proved 30% faster than using API call backs since the web application did not need to send a request to the server.                    </p>
                  </li>

                  <li className="flex items-start"> 
                  <strong><span className="text-teal-600 text-sm" style={{width: '1.25rem'}}> &gt; </span></strong>
                    <p className="pl-2 pb-1">
                      Designed and implemented the front-end of the application using Html and CSS.                   
                    </p>
                  </li>
                </ul>
              </div>
            {/* </h2> */}
          </div>
        </section>


        <section className="py-10 lg:px-96 ">
        <h4 className="text-s  text-gray-500 pt-8 font-medium">What's Next?</h4>
          <h3 className="text-teal-600 text-4xl pb-2 font-medium font-burtons">Get In Touch </h3>
          <p className=" mx-auto text-md pb-4 leading-8 text-gray-500 ">
            I'm always here to connect. Whether you have a question, new opportunities or just want to say hi. I’ll try my best to get back to you!
          </p>  

          <form action="mailto:matiabeya2@gmail.com" method="post" encType="text/plain">
            <div className="mb-4">
              <label className="block text-gray-700 text-sm font-bold mb-2" htmlFor="name">
                 Name
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="name"
                type="text"
                name="name"
                placeholder="Your Name"
                required
              />
            </div>
            <div className="mb-4">
              <label className="block text-gray-700 text-sm font-bold mb-2" htmlFor="email">
                Email
              </label>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="email"
                type="email"
                name="email"
                placeholder="Your Email"
                required
              />
            </div>
            <div className="mb-6">
              <label className="block text-gray-700 text-sm font-bold mb-2" htmlFor="message">
                Message
              </label>
              <textarea
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                id="message"
                name="message"
                rows="4"
                placeholder="Your Message"
                required
              ></textarea>
            </div>
            <div className="flex items-center justify-center">
              <button
                className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md"
                type="submit"
              >
                Send Message
              </button>
            </div>
          </form>
        </section>

      </main>
    </div>
  );
}
 